<a href="https://colab.research.google.com/github/bs3537/DS-Unit-1-Sprint-3-Statistical-Tests-and-Experiments/blob/master/Bhav_copy_LS_DS_131_Statistics_Probability_Assignment_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Science Unit 1 Sprint 3 Assignment 1
Apply the t-test to real data
Your assignment is to determine which issues have "statistically significant" differences between political parties in this 1980s congressional voting data. The data consists of 435 instances (one for each congressperson), a class (democrat or republican), and 16 binary attributes (yes or no for voting for or against certain issues). Be aware - there are missing values!

Your goals:

Load and clean the data (or determine the best method to drop observations when running tests)
Using hypothesis testing, find an issue that democrats support more than republicans with p < 0.01
Using hypothesis testing, find an issue that republicans support more than democrats with p < 0.01
Using hypothesis testing, find an issue where the difference between republicans and democrats has p > 0.1 (i.e. there may not be much of a difference)
Note that this data will involve 2 sample t-tests, because you're comparing averages across two groups (republicans and democrats) rather than a single group against a null hypothesis.

Stretch goals:

Refactor your code into functions so it's easy to rerun with arbitrary variables
Apply hypothesis testing to your personal project data (for the purposes of this notebook you can type a summary of the hypothesis you formed and tested)

In [0]:
#Load and clean the data (or determine the best method to drop observations when running tests

import pandas as pd
import numpy as np

In [0]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data')

In [3]:
df.head()

   republican  n  y n.1 y.1 y.2 y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
0  republican  n  y   n   y   y   y   n   n   n   n  n   y   y   y   n   ?
1    democrat  ?  y   y   ?   y   y   n   n   n   n  y   n   y   y   n   n
2    democrat  n  y   y   n   ?   y   n   n   n   n  y   n   y   n   n   y
3    democrat  y  y   y   n   y   y   n   n   n   n  y   ?   y   y   y   y
4    democrat  n  y   y   n   y   y   n   n   n   n  n   n   y   y   y   y

In [4]:
df.shape

(434, 17)

In [5]:
df.isnull().sum()
#pandas is not recognizing '?' values using this code

republican    0
n             0
y             0
n.1           0
y.1           0
y.2           0
y.3           0
n.2           0
n.3           0
n.4           0
y.4           0
?             0
y.5           0
y.6           0
y.7           0
n.5           0
y.8           0
dtype: int64

In [6]:
df.isnull().values.any()

False

In [0]:
# this function will replace ? values by null values
df.replace('?', np.nan, inplace=True)

In [8]:
df.isnull().sum()

republican      0
n              12
y              48
n.1            11
y.1            11
y.2            15
y.3            11
n.2            14
n.3            15
n.4            22
y.4             7
?              20
y.5            31
y.6            25
y.7            17
n.5            28
y.8           104
dtype: int64

In [9]:
df.dropna()
# the output below is now clean with all rows with ? value have been dropped.

     republican  n  y n.1 y.1 y.2 y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4      democrat  n  y   y   n   y   y   n   n   n   n  n   n   y   y   y   y
7    republican  n  y   n   y   y   y   n   n   n   n  n   y   y   y   n   y
18     democrat  y  y   y   n   n   n   y   y   y   n  y   n   n   n   y   y
22     democrat  y  y   y   n   n   n   y   y   y   n  n   n   n   n   y   y
24     democrat  y  n   y   n   n   n   y   y   y   y  n   n   n   n   y   y
25     democrat  y  n   y   n   n   n   y   y   y   n  y   n   n   n   y   y
26     democrat  y  y   y   n   n   n   y   y   y   n  y   n   n   n   y   y
27   republican  y  n   n   y   y   n   y   y   y   n  n   y   y   y   n   y
28     democrat  y  y   y   n   n   n   y   y   y   n  y   n   n   n   y   y
29   republican  n  y   n   y   y   y   n   n   n   n  n   y   y   y   n   n
31     democrat  y  y   y   n   n   n   y   y   y   y  n   n   y   n   y   y
32   republican  n  y   n   y   y   y   n   n   n   n  n   y   y   y   n   y
33     democrat  y  y   y   n   n   n   y   y   y   n  n   n   n   n   y   y
34   republican  n  y   n   y   y   y   n   n   n   n  n   y   y   y   n   n
36   republican  y  y   n   y   y   y   n   n   n   n  n   n   y   y   n   y
37   republican  n  y   n   y   y   y   n   n   n   y  n   y   y   y   n   n
38     democrat  y  n   y   n   n   n   y   y   y   y  y   n   y   n   y   y
41     democrat  y  n   y   n   n   n   y   y   y   n  n   n   n   n   n   y
42     democrat  y  n   y   n   n   n   y   y   y   n  n   n   n   n   y   y
45     democrat  y  y   y   n   n   n   y   y   y   n  n   n   n   n   n   y
47     democrat  y  y   y   n   n   n   y   y   n   n  n   n   n   y   n   y
49     democrat  y  y   y   n   n   n   y   y   y   n  y   n   n   n   y   y
52   republican  y  y   n   y   y   y   n   n   n   y  n   y   y   y   n   n
54   republican  n  y   n   y   y   y   n   n   n   y  y   y   y   y   n   n
55   republican  n  y   n   y   y   y   n   n   n   y  y   y   y   y   n   y
56   republican  n  y   n   y   y   y   n   n   n   y  n   y   y   y   n   y
57   republican  n  y   n   y   y   y   n   n   n   y  n   y   y   y   n   y
60   republican  n  y   n   y   y   y   n   n   n   n  n   y   y   y   n   n
62     democrat  y  y   y   n   n   n   y   y   y   n  y   n   n   n   n   y
64   republican  y  y   n   y   y   y   y   n   n   n  n   y   y   y   n   y
..          ... .. ..  ..  ..  ..  ..  ..  ..  ..  .. ..  ..  ..  ..  ..  ..
378  republican  n  n   n   y   y   y   n   n   n   n  n   y   y   y   n   y
382    democrat  y  y   y   n   y   y   n   y   y   y  y   n   n   n   n   y
383    democrat  y  y   y   y   y   y   n   n   n   n  y   y   y   y   n   y
384    democrat  y  y   n   n   y   y   n   n   n   n  y   y   y   y   y   n
390    democrat  y  y   n   n   n   n   n   y   y   n  y   n   n   n   y   n
391  republican  y  y   n   y   y   y   n   n   n   n  y   y   y   y   n   y
395    democrat  y  y   y   n   y   y   n   y   n   n  y   n   y   n   y   y
397    democrat  n  y   y   n   y   y   n   y   n   n  n   n   n   n   n   y
400  republican  n  y   n   y   y   y   n   n   n   y  y   y   y   y   n   n
403  republican  y  y   n   y   y   y   n   n   n   y  n   y   y   y   n   y
404  republican  n  n   n   y   y   y   n   n   n   n  n   y   y   y   n   y
405    democrat  y  n   y   n   y   y   n   n   y   y  n   n   y   y   n   y
406    democrat  n  n   n   y   y   y   n   n   n   n  y   y   y   y   n   n
408  republican  n  n   n   y   y   y   n   n   n   n  n   y   y   y   n   n
409  republican  n  n   n   y   y   y   n   n   n   n  y   y   y   y   n   y
410    democrat  y  n   y   n   n   y   y   y   y   y  y   n   n   n   n   y
411  republican  n  n   n   y   y   y   n   n   n   y  n   y   y   y   n   y
413    democrat  y  y   y   n   n   n   y   y   y   n  n   n   n   n   n   y
415  republican  y  y   n   y   y   y   n   n   n   y  n   n   y   y   n   y
416    democrat  y  y   y   n   n   n   y   y   y   y  y   n   y   n   n   y
417    democrat  y  y   y   n   n   n   y   y   n   y  n   n   n   n   n   y
418    democrat  y  y   y   n   n   n   y   y   y   n  n   n   n   n   n   y
419  republican  y  y   y   y   y   y   y   y   n   y  n   n   y   y   n   y
420    democrat  n  y   y   n   y   y   y   y   n   n  y   n   y   n   y   y
421    democrat  n  n   y   n   n   y   y   y   y   n  y   n   n   n   y   y
422    democrat  n  y   y   n   n   y   y   y   y   n  y   n   n   y   y   y
425    democrat  y  n   y   n   n   n   y   y   y   y  n   n   n   n   y   y
426  republican  n  n   n   y   y   y   y   y   n   y  n   y   y   y   n   y
429  republican  n  n   y   y   y   y   n   n   y   y  n   y   y   y   n   y
430    democrat  n  n   y   n   n   n   y   y   y   y  n   n   n   n   n   y

[232 rows x 17 columns]

In [10]:
df.dtypes

republican    object
n             object
y             object
n.1           object
y.1           object
y.2           object
y.3           object
n.2           object
n.3           object
n.4           object
y.4           object
?             object
y.5           object
y.6           object
y.7           object
n.5           object
y.8           object
dtype: object

In [0]:
#next step is converting categorical yes and no values to binary numeric values for statistical testing
df2 = df.rename(columns = {'republican': 'Party'})

In [12]:
df2.head()

        Party    n  y n.1  y.1  y.2 y.3 n.2  ... n.4 y.4  ?  y.5 y.6 y.7 n.5  y.8
0  republican    n  y   n    y    y   y   n  ...   n   n  n    y   y   y   n  NaN
1    democrat  NaN  y   y  NaN    y   y   n  ...   n   n  y    n   y   y   n    n
2    democrat    n  y   y    n  NaN   y   n  ...   n   n  y    n   y   n   n    y
3    democrat    y  y   y    n    y   y   n  ...   n   n  y  NaN   y   y   y    y
4    democrat    n  y   y    n    y   y   n  ...   n   n  n    n   y   y   y    y

[5 rows x 17 columns]

In [0]:
df3 = df2.dropna()

In [14]:
df3.head()

         Party  n  y n.1 y.1 y.2 y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  n  y   y   n   y   y   n   n   n   n  n   n   y   y   y   y
7   republican  n  y   n   y   y   y   n   n   n   n  n   y   y   y   n   y
18    democrat  y  y   y   n   n   n   y   y   y   n  y   n   n   n   y   y
22    democrat  y  y   y   n   n   n   y   y   y   n  n   n   n   n   y   y
24    democrat  y  n   y   n   n   n   y   y   y   y  n   n   n   n   y   y

In [15]:
df3.dtypes

Party    object
n        object
y        object
n.1      object
y.1      object
y.2      object
y.3      object
n.2      object
n.3      object
n.4      object
y.4      object
?        object
y.5      object
y.6      object
y.7      object
n.5      object
y.8      object
dtype: object

In [16]:
df3.head().T

             4           7         18        22        24
Party  democrat  republican  democrat  democrat  democrat
n             n           n         y         y         y
y             y           y         y         y         n
n.1           y           n         y         y         y
y.1           n           y         n         n         n
y.2           y           y         n         n         n
y.3           y           y         n         n         n
n.2           n           n         y         y         y
n.3           n           n         y         y         y
n.4           n           n         y         y         y
y.4           n           n         n         n         y
?             n           n         y         n         n
y.5           n           y         n         n         n
y.6           y           y         n         n         n
y.7           y           y         n         n         n
n.5           y           n         y         y         y
y.8           y           y         y         y         y

In [17]:
df3["n"].value_counts()

n    136
y     96
Name: n, dtype: int64

In [0]:
cleanup_df3 = {"n":     {"y": 1, "n": 0}}

In [19]:
df3.replace(cleanup_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y n.1 y.1 y.2 y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  y   y   n   y   y   n   n   n   n  n   n   y   y   y   y
7   republican  0  y   n   y   y   y   n   n   n   n  n   y   y   y   n   y
18    democrat  1  y   y   n   n   n   y   y   y   n  y   n   n   n   y   y
22    democrat  1  y   y   n   n   n   y   y   y   n  n   n   n   n   y   y
24    democrat  1  n   y   n   n   n   y   y   y   y  n   n   n   n   y   y

In [20]:
df3["y"].value_counts()

n    125
y    107
Name: y, dtype: int64

In [0]:
cleanup2_df3 = {"y":     {"y": 1, "n": 0}}

In [22]:
df3.replace(cleanup2_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y n.1 y.1 y.2 y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  1   y   n   y   y   n   n   n   n  n   n   y   y   y   y
7   republican  0  1   n   y   y   y   n   n   n   n  n   y   y   y   n   y
18    democrat  1  1   y   n   n   n   y   y   y   n  y   n   n   n   y   y
22    democrat  1  1   y   n   n   n   y   y   y   n  n   n   n   n   y   y
24    democrat  1  0   y   n   n   n   y   y   y   y  n   n   n   n   y   y

In [23]:
df3["n.1"].value_counts()

y    123
n    109
Name: n.1, dtype: int64

In [0]:
cleanup3_df3 = {"n.1":     {"y": 1, "n": 0}}

In [25]:
df3.replace(cleanup3_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1 y.1 y.2 y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  1    1   n   y   y   n   n   n   n  n   n   y   y   y   y
7   republican  0  1    0   y   y   y   n   n   n   n  n   y   y   y   n   y
18    democrat  1  1    1   n   n   n   y   y   y   n  y   n   n   n   y   y
22    democrat  1  1    1   n   n   n   y   y   y   n  n   n   n   n   y   y
24    democrat  1  0    1   n   n   n   y   y   y   y  n   n   n   n   y   y

In [26]:
df3["y.1"].value_counts()

n    119
y    113
Name: y.1, dtype: int64

In [0]:
cleanup4_df3 = {"y.1":     {"y": 1, "n": 0}}

In [28]:
df3.replace(cleanup4_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1 y.2 y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  1    1    0   y   y   n   n   n   n  n   n   y   y   y   y
7   republican  0  1    0    1   y   y   n   n   n   n  n   y   y   y   n   y
18    democrat  1  1    1    0   n   n   y   y   y   n  y   n   n   n   y   y
22    democrat  1  1    1    0   n   n   y   y   y   n  n   n   n   n   y   y
24    democrat  1  0    1    0   n   n   y   y   y   y  n   n   n   n   y   y

In [29]:
df3["y.2"].value_counts()

y    128
n    104
Name: y.2, dtype: int64

In [0]:
cleanup5_df3 = {"y.2":     {"y": 1, "n": 0}}

In [31]:
df3.replace(cleanup5_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2 y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  1    1    0    1   y   n   n   n   n  n   n   y   y   y   y
7   republican  0  1    0    1    1   y   n   n   n   n  n   y   y   y   n   y
18    democrat  1  1    1    0    0   n   y   y   y   n  y   n   n   n   y   y
22    democrat  1  1    1    0    0   n   y   y   y   n  n   n   n   n   y   y
24    democrat  1  0    1    0    0   n   y   y   y   y  n   n   n   n   y   y

In [32]:
df3["y.3"].value_counts()

y    149
n     83
Name: y.3, dtype: int64

In [0]:
cleanup6_df3 = {"y.3":     {"y": 1, "n": 0}}

In [34]:
df3.replace(cleanup6_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3 n.2 n.3 n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  1    1    0    1    1   n   n   n   n  n   n   y   y   y   y
7   republican  0  1    0    1    1    1   n   n   n   n  n   y   y   y   n   y
18    democrat  1  1    1    0    0    0   y   y   y   n  y   n   n   n   y   y
22    democrat  1  1    1    0    0    0   y   y   y   n  n   n   n   n   y   y
24    democrat  1  0    1    0    0    0   y   y   y   y  n   n   n   n   y   y

In [35]:
df3["n.2"].value_counts()

y    124
n    108
Name: n.2, dtype: int64

In [0]:
cleanup7_df3 = {"n.2":     {"y": 1, "n": 0}}

In [37]:
df3.replace(cleanup7_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  n.2  ... n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  1    1    0    1    1    0  ...   n   n  n   n   y   y   y   y
7   republican  0  1    0    1    1    1    0  ...   n   n  n   y   y   y   n   y
18    democrat  1  1    1    0    0    0    1  ...   y   n  y   n   n   n   y   y
22    democrat  1  1    1    0    0    0    1  ...   y   n  n   n   n   n   y   y
24    democrat  1  0    1    0    0    0    1  ...   y   y  n   n   n   n   y   y

[5 rows x 17 columns]

In [38]:
df3["n.3"].value_counts()

y    119
n    113
Name: n.3, dtype: int64

In [0]:
cleanup8_df3 = {"n.3":     {"y": 1, "n": 0}}

In [40]:
df3.replace(cleanup8_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  n.2  ...  n.4 y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  1    1    0    1    1    0  ...    n   n  n   n   y   y   y   y
7   republican  0  1    0    1    1    1    0  ...    n   n  n   y   y   y   n   y
18    democrat  1  1    1    0    0    0    1  ...    y   n  y   n   n   n   y   y
22    democrat  1  1    1    0    0    0    1  ...    y   n  n   n   n   n   y   y
24    democrat  1  0    1    0    0    0    1  ...    y   y  n   n   n   n   y   y

[5 rows x 17 columns]

In [41]:
df3["n.4"].value_counts()

n    119
y    113
Name: n.4, dtype: int64

In [0]:
cleanup9_df3 = {"n.4":     {"y": 1, "n": 0}}

In [43]:
df3.replace(cleanup9_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  n.2  ...  n.4  y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  1    1    0    1    1    0  ...    0    n  n   n   y   y   y   y
7   republican  0  1    0    1    1    1    0  ...    0    n  n   y   y   y   n   y
18    democrat  1  1    1    0    0    0    1  ...    1    n  y   n   n   n   y   y
22    democrat  1  1    1    0    0    0    1  ...    1    n  n   n   n   n   y   y
24    democrat  1  0    1    0    0    0    1  ...    1    y  n   n   n   n   y   y

[5 rows x 17 columns]

In [44]:
df3["y.4"].value_counts()

y    128
n    104
Name: y.4, dtype: int64

In [0]:
cleanup10_df3 = {"y.4":     {"y": 1, "n": 0}}

In [46]:
df3.replace(cleanup10_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  n.2  ...  n.4  y.4  ? y.5 y.6 y.7 n.5 y.8
4     democrat  0  1    1    0    1    1    0  ...    0    0  n   n   y   y   y   y
7   republican  0  1    0    1    1    1    0  ...    0    0  n   y   y   y   n   y
18    democrat  1  1    1    0    0    0    1  ...    1    0  y   n   n   n   y   y
22    democrat  1  1    1    0    0    0    1  ...    1    0  n   n   n   n   y   y
24    democrat  1  0    1    0    0    0    1  ...    1    1  n   n   n   n   y   y

[5 rows x 17 columns]

In [47]:
df3["?"].value_counts()

n    152
y     80
Name: ?, dtype: int64

In [0]:
cleanup11_df3 = {"?":     {"y": 1, "n": 0}}

In [49]:
df3.replace(cleanup11_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  n.2  ...  n.4  y.4  ?  y.5 y.6 y.7 n.5 y.8
4     democrat  0  1    1    0    1    1    0  ...    0    0  0    n   y   y   y   y
7   republican  0  1    0    1    1    1    0  ...    0    0  0    y   y   y   n   y
18    democrat  1  1    1    0    0    0    1  ...    1    0  1    n   n   n   y   y
22    democrat  1  1    1    0    0    0    1  ...    1    0  0    n   n   n   y   y
24    democrat  1  0    1    0    0    0    1  ...    1    1  0    n   n   n   y   y

[5 rows x 17 columns]

In [50]:
df3["y.5"].value_counts()

n    124
y    108
Name: y.5, dtype: int64

In [0]:
cleanup12_df3 = {"y.5":     {"y": 1, "n": 0}}

In [52]:
df3.replace(cleanup12_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  n.2  ...  n.4  y.4  ?  y.5  y.6 y.7 n.5 y.8
4     democrat  0  1    1    0    1    1    0  ...    0    0  0    0    y   y   y   y
7   republican  0  1    0    1    1    1    0  ...    0    0  0    1    y   y   n   y
18    democrat  1  1    1    0    0    0    1  ...    1    0  1    0    n   n   y   y
22    democrat  1  1    1    0    0    0    1  ...    1    0  0    0    n   n   y   y
24    democrat  1  0    1    0    0    0    1  ...    1    1  0    0    n   n   y   y

[5 rows x 17 columns]

In [53]:
df3["y.6"].value_counts()

y    127
n    105
Name: y.6, dtype: int64

In [0]:
cleanup13_df3 = {"y.6":     {"y": 1, "n": 0}}

In [55]:
df3.replace(cleanup13_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  ...  y.4  ?  y.5  y.6  y.7  n.5  y.8
4     democrat  0  1    1    0    1    1  ...    0  0    0    1    y    y    y
7   republican  0  1    0    1    1    1  ...    0  0    1    1    y    n    y
18    democrat  1  1    1    0    0    0  ...    0  1    0    0    n    y    y
22    democrat  1  1    1    0    0    0  ...    0  0    0    0    n    y    y
24    democrat  1  0    1    0    0    0  ...    1  0    0    0    n    y    y

[5 rows x 17 columns]

In [56]:
df3["y.7"].value_counts()

y    149
n     83
Name: y.7, dtype: int64

In [0]:
cleanup14_df3 = {"y.7":     {"y": 1, "n": 0}}

In [58]:
df3.replace(cleanup14_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  ...  y.4  ?  y.5  y.6  y.7  n.5  y.8
4     democrat  0  1    1    0    1    1  ...    0  0    0    1    1    y    y
7   republican  0  1    0    1    1    1  ...    0  0    1    1    1    n    y
18    democrat  1  1    1    0    0    0  ...    0  1    0    0    0    y    y
22    democrat  1  1    1    0    0    0  ...    0  0    0    0    0    y    y
24    democrat  1  0    1    0    0    0  ...    1  0    0    0    0    y    y

[5 rows x 17 columns]

In [59]:
df3["n.5"].value_counts()

n    146
y     86
Name: n.5, dtype: int64

In [0]:
cleanup15_df3 = {"n.5":     {"y": 1, "n": 0}}

In [61]:
df3.replace(cleanup15_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  ...  y.4  ?  y.5  y.6  y.7  n.5  y.8
4     democrat  0  1    1    0    1    1  ...    0  0    0    1    1    1    y
7   republican  0  1    0    1    1    1  ...    0  0    1    1    1    0    y
18    democrat  1  1    1    0    0    0  ...    0  1    0    0    0    1    y
22    democrat  1  1    1    0    0    0  ...    0  0    0    0    0    1    y
24    democrat  1  0    1    0    0    0  ...    1  0    0    0    0    1    y

[5 rows x 17 columns]

In [62]:
df3["y.8"].value_counts()

y    189
n     43
Name: y.8, dtype: int64

In [0]:
cleanup16_df3 = {"y.8":     {"y": 1, "n": 0}}

In [64]:
df3.replace(cleanup16_df3, inplace=True)
df3.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  regex=regex)

         Party  n  y  n.1  y.1  y.2  y.3  ...  y.4  ?  y.5  y.6  y.7  n.5  y.8
4     democrat  0  1    1    0    1    1  ...    0  0    0    1    1    1    1
7   republican  0  1    0    1    1    1  ...    0  0    1    1    1    0    1
18    democrat  1  1    1    0    0    0  ...    0  1    0    0    0    1    1
22    democrat  1  1    1    0    0    0  ...    0  0    0    0    0    1    1
24    democrat  1  0    1    0    0    0  ...    1  0    0    0    0    1    1

[5 rows x 17 columns]

In [81]:
df3.dtypes

Party    object
n         int64
y         int64
n.1       int64
y.1       int64
y.2       int64
y.3       int64
n.2       int64
n.3       int64
n.4       int64
y.4       int64
?         int64
y.5       int64
y.6       int64
y.7       int64
n.5       int64
y.8       int64
dtype: object

### Thus, all the categorical variables have been coded as binary variables and can now be used for statistical analysis.

In [84]:
# let us look at issue of handicapped infants first
# n = handicapped_infants issue
#1= yes vote, n = no vote
df4 = df3[['Party', 'n']]
df4.head()

         Party  n
4     democrat  0
7   republican  0
18    democrat  1
22    democrat  1
24    democrat  1

In [0]:
df4_rep = df4[df4['Party']=='republican']
df4_dem = df4[df4['Party']=='democrat']

In [94]:
df5 = df4_rep[df4_rep['n']== 1]
df5.head()

         Party  n
27  republican  1
36  republican  1
52  republican  1
64  republican  1
70  republican  1

In [95]:
df5.shape

(23, 2)

In [91]:
df6 = df4_dem[df4_dem['n']== 1]
df6.head()

       Party  n
18  democrat  1
22  democrat  1
24  democrat  1
25  democrat  1
26  democrat  1

In [96]:
df6.shape

(73, 2)

In [0]:
# democrats have 73 yes votes on this issue of handicapped infants while republicans have 23 yes votes on this issue which seems significant.
# we have to next do an inferential test to find p value.

In [104]:
#creating a crosstab table for frequency distribution for issue of handicapped infants
n_crosstab = pd.crosstab(df4.Party, df4.n, normalize='columns')
n_crosstab

n               0         1
Party
democrat    0.375  0.760417
republican  0.625  0.239583

In [0]:
# since we are comparing proportions, we have to apply z test

In [0]:
import numpy as np
import scipy.stats as st
import scipy.special as sp
# n = number of obervations of yes and no
n = 100  
# h = number of yes votes for democrats on this issue
h = 76  
# q = null-hypothesis of no difference in yes and no votes
q = .5

In [108]:
# z score calculation

xbar = float(h) / n
z = (xbar - q) * np.sqrt(n / (q * (1 - q)))
# We don't want to display more than 4 decimals.
z

5.2

In [109]:
pval = 2 * (1 - st.norm.cdf(z))
pval

1.9928852634798488e-07

In [0]:
#The p value here is very low and lower than 0.01, so our z score calculation was successful in calculating the p value in this case

####Democrats support the issue of handicapped infants more than republicans with a p value < 0.01.

In [113]:
df3_group = df3.groupby('Party').mean()
df3_group

                   n         y       n.1  ...       y.7       n.5       y.8
Party                                     ...
democrat    0.588710  0.451613  0.854839  ...  0.346774  0.596774  0.943548
republican  0.212963  0.472222  0.157407  ...  0.981481  0.111111  0.666667

[2 rows x 16 columns]

In [0]:
# For issue y.1 = physician-fee-freeze, republicans seem to be voting more yes, let us evaluate this using same z score method as above

In [114]:
df7 = df3[['Party', 'y.1']]
df7.head()

         Party  y.1
4     democrat    0
7   republican    1
18    democrat    0
22    democrat    0
24    democrat    0

In [118]:
df8 = df7.rename(columns = {'y.1' : 'phy'})
df8.head()

         Party  phy
4     democrat    0
7   republican    1
18    democrat    0
22    democrat    0
24    democrat    0

In [119]:
y1_crosstab = pd.crosstab(df8.Party, df8.phy, normalize='columns')
y1_crosstab

phy                0         1
Party
democrat    0.991597  0.053097
republican  0.008403  0.946903

In [0]:
# from above output, the number of yes votes for this issue of physician fee freeze is 94% for republicans and 5.3% for democrats. 
# Let us now do a z test to find p value.

In [0]:
# n = number of obervations of yes and no
n2 = 100  
# h = number of yes votes for republicans on this issue
h2 = 94.6  
# q = null-hypothesis of no difference in yes and no votes
q2 = .5

In [121]:
# z score calculation

xbar = float(h2) / n2
z2 = (xbar - q2) * np.sqrt(n2 / (q2 * (1 - q2)))
# We don't want to display more than 4 decimals.
z2

8.919999999999998

In [122]:
pval2 = 2 * (1 - st.norm.cdf(z2))
pval2

0.0

### The p value is 0.0 which is <0.01, so republicans support the issue of physicians fee freeze more than democrats with p value <0.01.

In [0]:
# For issue y=water-project-cost-sharing, there doesn't seem much difference in yes votes in two parties.

In [123]:
df9 = df3[['Party', 'y']]
df9.head()

         Party  y
4     democrat  1
7   republican  1
18    democrat  1
22    democrat  1
24    democrat  0

In [124]:
y2_crosstab = pd.crosstab(df9.Party, df9.y, normalize='columns')
y2_crosstab

y               0         1
Party
democrat    0.544  0.523364
republican  0.456  0.476636

In [0]:
# from the above cross tab, yes votes for democrats on this issue are 52.3% and for republicans are 47.6%.
# Let us do a z test to find p value.

In [0]:
# n = number of obervations of yes and no
n3 = 100  
# h = number of yes votes for democrats on this issue
h3 = 52.3 
# q = null-hypothesis of no difference in yes and no votes
q3 = .5

In [126]:
# z score calculation

xbar = float(h3) / n3
z3 = (xbar - q3) * np.sqrt(n3 / (q3 * (1 - q3)))
# We don't want to display more than 4 decimals.
z3

0.4600000000000004

In [127]:
pval3 = 2 * (1 - st.norm.cdf(z3))
pval3

0.6455162205006952

### The p value is 0.64 which is >0.01, so not significant. There is no significant difference in yes votes for republicans and democrats on the issue of water-project-cost-sharing. The p value is also >0.1.